version: 2

sources:
  - name: raw
    database: marketpulse360
    schema: public
    tables:
      - name: raw_orders
      - name: raw_order_items
      - name: raw_customers
      - name: raw_products
      - name: raw_payments
      - name: raw_reviews
      - name: raw_sellers
      - name: raw_category_translation